version: "3.0"

services:
  frontend:
    build: ./react-app
    ports:
      - "3000:3000"
    volumes:
      - ./react-app/src:/app/src
      - ./react-app/public:/app/public
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: ./php-app
      args:
        user: "${USER:-www-data}"
        uid: "${UID:-1000}"
    ports:
      - "8000:80"
    volumes:
      - vendor:/var/www/html/vendor
      - ./php-app/src:/var/www/html
volumes:
  node_modules:
  vendor:
